### ISSUE TITLE
Xcode 11.4 beta (11N111s) fails to build projects that depend on LaunchDarkly

### ISSUE THREAD

**Issue by brandon-haugen** [launchdarkly/ios-client#207] opened 2020-02-11 17:21 UTC
**Is this a support request?**
**No**, this is an issue with the SDK compiling when included in an iOS project being built with Xcode Version 11.4 beta (11N111s)

**Describe the bug**
Building iOS projects, that depend upon LaunchDarkly, using Xcode Version 11.4 beta (11N111s) fail with a compiler error.

> Pods/LaunchDarkly/LaunchDarkly/LaunchDarkly/LDClient.swift:639:28: error: protocol 'Collection' can only be used as a generic constraint because it has Self or associated type requirements
            + (fallback is Collection ? " The fallback value type is a collection. Make sure the element of the fallback value's type is not too restrictive for the actual feature flag type." : "")

**To reproduce**
- Attempt to build a project that relies on LaunchDarkly using Xcode Version 11.4 beta (11N111s)

**Expected behavior**
- The project builds and runs as expected

**Logs**
> Pods/LaunchDarkly/LaunchDarkly/LaunchDarkly/LDClient.swift:639:28: error: protocol 'Collection' can only be used as a generic constraint because it has Self or associated type requirements
            + (fallback is Collection ? " The fallback value type is a collection. Make sure the element of the fallback value's type is not too restrictive for the actual feature flag type." : "")

**SDK version**
- 4.1.2 - what we are using in production builds
- 4.4.0 - latest version available that I tried before reporting the issue in case it was already fixed

**Language version, developer tools**
- Swift 
- Xcode 11.4 beta (11N111s)

**OS/platform**
- Building on macOS using Xcode Version 11.4 beta (11N111s)

**Additional context**
Xcode Version 11.4 beta (11N111s) was just released a week or so ago, I am still in the iOS betas so I had to upgrade to the latest Xcode to build/debug with my personal iOS device 😢

**Comment by bwoskow-ld** [comment] 2020-02-13 17:18
Hi @brandon-haugen,

Thanks for letting us know. We'll take a look at upgrading to the XCode beta to reproduce and fix the issue. Generally we don't guarantee compatibility with beta versions of downstream dependencies but we do understand the situation that you're in.

_Tracked internally as 65670._

**Comment by brandon-haugen** [comment] 2020-02-13 17:21
Thanks @bwoskow-ld! Just to be clear, this is not blocking me from anything other than testing on my own personal device so it is not a major issue for me, it just appears to be something that will need to be addressed before Xcode 11.4 goes out publicly unless Apple changes what is included in it and this error does not occur.

**Comment by kielgillard** [comment] 2020-02-14 05:45
There's another error, too:
```
-sectalign and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```

**Comment by torchhound** [comment] 2020-02-21 23:07
Hi @brandon-haugen we have now written internal fixes for the Xcode 11.4 build errors and warnings. 

Hi @kielgillard I was unable to replicate that specific error.

**Comment by jdeff** [comment] 2020-03-24 22:06
11.4 is now public.

**Comment by michalsrutek** [comment] 2020-03-25 08:58
@torchhound @bwoskow-ld Were you able to resolve this? Do you have a timetable for when you could release it to the public?

**Comment by lietusme** [comment] 2020-03-25 10:39
Need fix for this ASAP

**Comment by Oleg-Marchik-Neklo** [comment] 2020-03-25 10:53
@torchhound  just remove this line
`+ (fallback is Collection ? " The fallback value type is a collection. Make sure the element of the fallback value's type is not too restrictive for the actual feature flag type." : "")`
and build bug will be fixed

**Comment by bwoskow-ld** [comment] 2020-03-25 16:57
We resumed work on this yesterday once the GA was made available. At the moment we're working through some test failures as one of our test dependencies doesn't work as expected with Xcode 11.4.

We'll update this issue when a new version with the fix is available. We expect to have this out in the next couple days. Thank you for your patience.

**Comment by nraptis** [comment] 2020-03-25 20:12
Please fix. Can't compile code with your library.

**Comment by AnthonySmith01** [comment] 2020-03-26 05:02
Hi All, thanks for LaunchDarkly it is great.

Any ETA on this fix? XCode 11.4 is now public and out of beta.

**Comment by idrougge** [comment] 2020-03-26 09:34
I was holding off running any betas because of this, can't believe it is still a thing when the GM release is out.

**Comment by hariDasu** [comment] 2020-03-26 18:48
+1 for this, currently downgrading to 11.3 since we rely on this tool so heavily!

**Comment by torchhound** [comment] 2020-03-27 05:05
Hi all, Xcode 11.4 support was just added in iOS client SDK version 4.5.0.

**Closed as completed by torchhound** 2020-03-27 05:05 UTC
