### ISSUE TITLE
Crash when calling `LDClient.start` with large `startWaitSeconds` on Apple Silicon

### ISSUE THREAD

**Issue by borodindr** [launchdarkly/ios-client#392] opened 2024-06-06 00:44 UTC
**Describe the bug**
When calling `LDClient.start` method with `startWaitSeconds` greater than 15, app crashes when it is trying to log the message. Happens only when a project running on Apple Silicon Mac with MacOS 14.4 or higher. Please don't be confused with Run Destination, it can be any.

**To reproduce**
Required equipment:
- Mac with Apple Silicon (M1, M2 etc)
- MacOS 14.4 or higher

Call the following anywhere on app launch:

```swift
let config = LDConfig(mobileKey: "key", autoEnvAttributes: .disabled)
LDClient.start(config: config, startWaitSeconds: 60)
```

**Expected behavior**
Log message is displayed and the app continue to work.

**Logs**
Screenshot of the crash:
<img width="1241" alt="Screenshot 2024-06-05 at 7 21 32 PM" src="https://github.com/launchdarkly/ios-client-sdk/assets/46873400/fe0d9796-d504-4fa8-9d4e-6fafc13d1d9d">

**Library version**
LaunchDarkly 9.8.0 and 9.8.1.

**XCode and Swift version**
- Xcode - reproduced on 15.4 and 15.3
- Swift - 5.9
- Run from MacOS 14.4 or higher with Apple Silicon
- Run destination - MacOS 14.4+ or any iOS

**Platform the issue occurs on**
All platforms if project ran from Xcode on MacOS 14.4 or higher with Apple Silicon

**Additional context**
When calling `os_log` in `LDClient.start` method (line 792 in LDClient.swift file), the message has 3 parameters: `%s`, `%d` and `%s` or *string*, *decimal* and *string*. But then arguments passed are `String`, `Double` and `Double`. On older MacOS versions, if argument type doesn't match, it will log `(null)` but starting from MacOS 14.4 on Apple Silicon it produces an exception. 

Possible solution could be changing the third argument in the log message from `%s` to `%d` like below:

```swift
os_log("%s LDClient.start was called with a timeout greater than %d seconds. We recommend a timeout of less than %d seconds.", log: config.logger, type: .debug, self.typeName(and: #function), LDClient.longTimeoutInterval, LDClient.longTimeoutInterval)
```

**Comment by tanderson-ld** [comment] 2024-06-06 14:19
@borodindr , thank you for reporting this and we appreciate the extra info you collected.  We will take a look and release a fix when ready.

**Comment by tanderson-ld** [comment] 2024-06-07 21:26
[A PR has been opened for this issue and will be merged/released in the next few days.](https://github.com/launchdarkly/ios-client-sdk/pull/393)

**Comment by borodindr** [comment] 2024-06-08 00:44
Great! Thank you for the quick response.

**Comment by tanderson-ld** [comment] 2024-06-10 14:20
@borodindr , version 9.8.2 has been released and this issue should be fixed.  I wasn't able to reproduce the issue myself since I don't have that specific device.  Please let us know whether or not this resolves the issue for you.  Thank you.

**Comment by borodindr** [comment] 2024-06-12 20:57
@tanderson-ld version 9.8.2 was validated and the issue is fixed. Thank you!

**Comment by tanderson-ld** [comment] 2024-06-12 21:46
@borodindr , thank you for positively confirming!

**Closed as completed by tanderson-ld** 2024-06-12 21:46 UTC
